### PR TITLE
Change fortinet_policy.py to work with new version of FortiManager 

### PR DESCRIPTION
**Pull request by jinpingh**
FortiManager have been updated  in Salem lab with new version . Leo Lam changed JSON RPC API to work with new version of FortiManager .

### CODE REVIEW

**Review by LindsayHill — CHANGES_REQUESTED** [review]
Please rename your workflow files. Remove 'meta' from the names - so actions/workflows/create_policy.meta.yaml should become actions/workflows/create_policy.yaml

**Comment by jinpingh** [comment]
@LindsayHill  Did changes. Once lab is up running, will test changes and submit code.
Thanks!

**Comment by jinpingh** [comment]
@LindsayHill tested and submitted code

**Comment by dzimine** [comment]
@jinpingh Great contribution, way to go!!! Thanks!

**Pull request closed without merging**
